# Generated by Django 4.0.4 on 2022-04-29 18:34

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='body',
            field=wagtail.fields.StreamField([('title', wagtail.blocks.CharBlock(form_classname='full title', template='blocks/title_block.html')), ('richtext', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True, use_json_field=None),
        ),
    ]
