# Generated by Django 4.0.4 on 2022-04-29 19:23

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetailpage',
            name='body',
            field=wagtail.fields.StreamField([('title_and_subtitle', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=100, required=True)), ('subtitle', wagtail.blocks.CharBlock(max_length=250, required=False))]))], blank=True, null=True, use_json_field=None),
        ),
    ]
