# Generated by Django 4.0.4 on 2022-04-29 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetailpage',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.productcategory'),
        ),
    ]
